version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - '443:443'
    volumes:
      - nginx:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    networks:
      - smartbutton
    depends_on:
      - emqx

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_URL: ${MQTT_URL}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    networks:
      - smartbutton

  letsencrypt:
    image: certbot/certbot
    ports:
      - '80:80'
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot :/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - smartbutton

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx:/opt/emqx
    networks:
      - smartbutton

networks:
  smartbutton:

volumes:
  emqx:
  certbot:
  letsencrypt:
  nginx: